version: '3.8'
services:

  app:
    
    image: n3mnuonghn/aeroponiciot:1.0.0
    container_name: aeroponiciot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5062:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=14.225.202.137,1433;Database=AeroponicIOT;User Id=sa;Password=ResoSQL123456@;TrustServerCertificate=true;
    depends_on:
      - mssql
    restart: unless-stopped
