// <auto-generated />
using System;
using AeroponicIOT.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AeroponicIOT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260325030105_AddSensorRawPrecisionFields")]
    partial class AddSensorRawPrecisionFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AeroponicIOT.Models.ActuatorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("action");

                    b.Property<string>("ActuatorType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("actuator_type");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Timestamp");

                    b.ToTable("actuator_logs");
                });

            modelBuilder.Entity("AeroponicIOT.Models.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlertType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("alert_type");

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit")
                        .HasColumnName("is_resolved");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("severity");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("alerts");
                });

            modelBuilder.Entity("AeroponicIOT.Models.AutomationRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("action");

                    b.Property<int>("ActuatorType")
                        .HasColumnType("int")
                        .HasColumnName("actuator_type");

                    b.Property<string>("ConditionOperator")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("condition_operator");

                    b.Property<string>("ConditionParameter")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("condition_parameter");

                    b.Property<decimal?>("ConditionValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("condition_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastExecuted")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_executed");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("rule_name");

                    b.Property<int>("RuleType")
                        .HasColumnType("int")
                        .HasColumnName("rule_type");

                    b.Property<string>("ScheduleDays")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("schedule_days");

                    b.Property<TimeOnly?>("ScheduleTime")
                        .HasColumnType("time")
                        .HasColumnName("schedule_time");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("automation_rules");
                });

            modelBuilder.Entity("AeroponicIOT.Models.Crop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("TotalDaysEst")
                        .HasColumnType("int")
                        .HasColumnName("total_days_est");

                    b.HasKey("Id");

                    b.ToTable("crops");
                });

            modelBuilder.Entity("AeroponicIOT.Models.CropStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CropId")
                        .HasColumnType("int")
                        .HasColumnName("crop_id");

                    b.Property<int?>("DayEnd")
                        .HasColumnType("int")
                        .HasColumnName("day_end");

                    b.Property<int?>("DayStart")
                        .HasColumnType("int")
                        .HasColumnName("day_start");

                    b.Property<int?>("HumidityMax")
                        .HasColumnType("int")
                        .HasColumnName("humidity_max");

                    b.Property<int?>("HumidityMin")
                        .HasColumnType("int")
                        .HasColumnName("humidity_min");

                    b.Property<decimal?>("PhMax")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ph_max");

                    b.Property<decimal?>("PhMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ph_min");

                    b.Property<int?>("PpmMax")
                        .HasColumnType("int")
                        .HasColumnName("ppm_max");

                    b.Property<int?>("PpmMin")
                        .HasColumnType("int")
                        .HasColumnName("ppm_min");

                    b.Property<int?>("PumpOffMinutes")
                        .HasColumnType("int")
                        .HasColumnName("pump_off_minutes");

                    b.Property<int?>("PumpOnMinutes")
                        .HasColumnType("int")
                        .HasColumnName("pump_on_minutes");

                    b.Property<string>("StageName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("stage_name");

                    b.Property<int?>("WaterTempMax")
                        .HasColumnType("int")
                        .HasColumnName("water_temp_max");

                    b.Property<int?>("WaterTempMin")
                        .HasColumnType("int")
                        .HasColumnName("water_temp_min");

                    b.HasKey("Id");

                    b.HasIndex("CropId");

                    b.ToTable("crop_stages");
                });

            modelBuilder.Entity("AeroponicIOT.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChipId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("chip_id");

                    b.Property<string>("ClaimCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("claim_code");

                    b.Property<DateTime?>("ClaimCodeExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("claim_code_expires_at");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("CropAssignedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("crop_assigned_at");

                    b.Property<int?>("CurrentCropId")
                        .HasColumnType("int")
                        .HasColumnName("current_crop_id");

                    b.Property<string>("DeviceName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("device_name");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("firmware_version");

                    b.Property<int?>("GardenId")
                        .HasColumnType("int")
                        .HasColumnName("garden_id");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_seen");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("mac_address");

                    b.Property<DateTime?>("ProvisionedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("provisioned_at");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ClaimCode")
                        .IsUnique()
                        .HasFilter("[claim_code] IS NOT NULL");

                    b.HasIndex("CurrentCropId");

                    b.HasIndex("GardenId");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("AeroponicIOT.Models.Garden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("gardens");
                });

            modelBuilder.Entity("AeroponicIOT.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("read_at");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("AeroponicIOT.Models.SensorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int")
                        .HasColumnName("device_id");

                    b.Property<int?>("Humidity")
                        .HasColumnType("int")
                        .HasColumnName("humidity");

                    b.Property<decimal?>("HumidityRaw")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("humidity_raw");

                    b.Property<int?>("LightIntensity")
                        .HasColumnType("int")
                        .HasColumnName("light_intensity");

                    b.Property<decimal?>("LightIntensityRaw")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("light_intensity_raw");

                    b.Property<decimal?>("Ph")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ph");

                    b.Property<int?>("TdsPpm")
                        .HasColumnType("int")
                        .HasColumnName("tds_ppm");

                    b.Property<decimal?>("TdsRaw")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tds_raw");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.Property<int?>("WaterTemp")
                        .HasColumnType("int")
                        .HasColumnName("water_temp");

                    b.Property<decimal?>("WaterTempRaw")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("water_temp_raw");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "Timestamp");

                    b.ToTable("sensor_logs");
                });

            modelBuilder.Entity("AeroponicIOT.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[username] IS NOT NULL");

                    b.ToTable("users");
                });

            modelBuilder.Entity("AeroponicIOT.Models.ActuatorLog", b =>
                {
                    b.HasOne("AeroponicIOT.Models.Device", "Device")
                        .WithMany("ActuatorLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AeroponicIOT.Models.Alert", b =>
                {
                    b.HasOne("AeroponicIOT.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AeroponicIOT.Models.AutomationRule", b =>
                {
                    b.HasOne("AeroponicIOT.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AeroponicIOT.Models.CropStage", b =>
                {
                    b.HasOne("AeroponicIOT.Models.Crop", "Crop")
                        .WithMany("CropStages")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");
                });

            modelBuilder.Entity("AeroponicIOT.Models.Device", b =>
                {
                    b.HasOne("AeroponicIOT.Models.Crop", "Crop")
                        .WithMany("Devices")
                        .HasForeignKey("CurrentCropId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AeroponicIOT.Models.Garden", "Garden")
                        .WithMany("Devices")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AeroponicIOT.Models.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Crop");

                    b.Navigation("Garden");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AeroponicIOT.Models.Notification", b =>
                {
                    b.HasOne("AeroponicIOT.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AeroponicIOT.Models.SensorLog", b =>
                {
                    b.HasOne("AeroponicIOT.Models.Device", "Device")
                        .WithMany("SensorLogs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("AeroponicIOT.Models.Crop", b =>
                {
                    b.Navigation("CropStages");

                    b.Navigation("Devices");
                });

            modelBuilder.Entity("AeroponicIOT.Models.Device", b =>
                {
                    b.Navigation("ActuatorLogs");

                    b.Navigation("SensorLogs");
                });

            modelBuilder.Entity("AeroponicIOT.Models.Garden", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("AeroponicIOT.Models.User", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
