using AeroponicIOT.Services.Notifications;

namespace AeroponicIOT.Services.AI;

/// <summary>
/// Represents a suggestion generated by the AI analysis of sensor data.
/// </summary>
public class AiSuggestionResult
{
    /// <summary>A short, actionable title for the suggestion.</summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>Detailed suggestion message with reasoning and actionable advice.</summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>The notification severity level.</summary>
    public NotificationType Type { get; set; } = NotificationType.Info;

    /// <summary>
    /// Optional suggested actuator action (e.g., "pump:ON", "light:OFF").
    /// Can be parsed by the automation layer.
    /// </summary>
    public string? SuggestedAction { get; set; }

    /// <summary>Confidence score 0-100.</summary>
    public int Confidence { get; set; }
}

/// <summary>
/// Lightweight record stored to track the last AI suggestion per device (cooldown).
/// </summary>
public class AiSuggestionCacheEntry
{
    public int DeviceId { get; set; }
    public string Suggestion { get; set; } = string.Empty;
    public DateTime GeneratedAt { get; set; }
}
